---
- name: Update and upgrade all Ubuntu/Debian hosts
  hosts: servers
  become: yes

  tasks:
    - name: Ensure 'at' daemon is installed
      apt:
        name: at
        state: present
        update_cache: yes

    - name: Ensure 'atd' service is running
      systemd:
        name: atd
        enabled: yes
        state: started

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        autoremove: yes
        autoclean: yes

    - name: Check if a reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Schedule reboot in 24 hours if required
      when: reboot_required.stat.exists
      shell: |
        echo "shutdown -r now" | at now + 24 hours
      args:
        executable: /bin/bash
